<a href="https://colab.research.google.com/github/ANSHIKA-MOURYA/Python/blob/main/Introduction_to_linear_algebrapynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LINEAR ALGEBRA FOR DATA SCIENCE

SCALARS(0 Dimension Tensor) in base python

In [ ]:
x=25
x

In [ ]:
type(x)

In [ ]:
y=4

In [ ]:
py_sum=x+y
py_sum

In [ ]:
type(py_sum)

SCALARS IN PYTORCH

In [ ]:
import torch

In [ ]:
x_pt=torch.tensor(25)
x_pt

In [ ]:
x_pt.shape

SCALARS IN Tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
x_tf=tf.Variable(25, dtype=tf.int16)
x_tf

In [ ]:
x_tf.shape

In [ ]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [ ]:
x_tf+y_tf

In [ ]:
tf_sum = tf.add(x_tf,y_tf)
tf_sum

In [ ]:
tf_sum.numpy()#NumPy operations automatically convert tensors to Numpy arrays, and vice versa

VECTORS (1 Dimension Tensor)

In [17]:
import numpy as np

In [19]:
x=np.array([23,3,12])

x[0]

23

In [20]:
len(x)

3

In [21]:
x.shape

(3,)

In [22]:
type(x[0])

numpy.int64

Vector Transpose

In [23]:
#transposing a 1D array has no effect
x_t=x.T
x_t

array([23,  3, 12])

In [24]:
x.shape

(3,)

In [25]:
#..but it doew we use nested'matrix-xtyle' brackets:
y=np.array([[23,2,12]])
y

array([[23,  2, 12]])

In [26]:
y.shape

(1, 3)

In [27]:
#..we can transpose a matrix with a dimension of length 1, which is mathematically equivalent:
y_t=y.T
y_t

array([[23],
       [ 2],
       [12]])

In [29]:
y_t.shape

(3, 1)

Vectoer In PyTorch and TensorFlow

In [30]:
x_pt=torch.tensor([25,2,12])
x_pt

tensor([25,  2, 12])

In [31]:
x_tf=tf.Variable([12,2,23])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([12,  2, 23], dtype=int32)>

In [32]:
x_tf.numpy()

array([12,  2, 23], dtype=int32)